version: '3.9'

services:

  slam:
    image: tccoin/torch_splatting:latest
    container_name: torch_splatting
    network_mode: host
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "TERM=xterm-256color"
      - "XAUTHORITY"
    working_dir: "/home/${USER}/projects/NeRF-SLAM/"
    privileged: true
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/${USER}/.Xauthority:rw
      - .zshrc:/home/${USER}/.zshrc:rw
      - .zsh_history:/home/${USER}/.zsh_history:rw
      - /home/$USER/Projects/NeRF-SLAM:/home/${USER}/projects/NeRF-SLAM/
      - /media/sdg1/:/home/${USER}/dataset/
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [ gpu ]
    entrypoint: /bin/zsh
